[tool.ruff]
# Target Python 3.11 so built-ins like `BaseExceptionGroup` are recognised.
# This eliminates F821 undefined-name errors in upstream HA core tests.

target-version = "py311"

# Optionally skip heavy upstream core tests; keep our own under `config/`.
exclude = [
    # Entire upstream HA *tests* tree is kept only for reference.  They rely
    # on Python ≥3.12 features unknown to Ruff when *target-version* = "py311".
    "tests/**",
    # Scaffold helpers shipped with the component template – not lint-worthy
    "script/**",
]

# Extra safety net: ignore *undefined-name* inside any file that still slips
# through the exclude filters (e.g. when a CI task lints a single file).
per-file-ignores = {
    "tests/*": ["F821"],
}