play_preset:
  name: Play Preset
  description: Play a preset on the WiiM device.
  fields:
    entity_id:
      name: Entity
      description: Name of the WiiM entity to control.
      selector:
        entity:
          domain: media_player
          integration: wiim
    preset:
      name: Preset
      description: Preset number to play (1-6).
      selector:
        number:
          min: 1
          max: 6
          step: 1

toggle_power:
  name: Toggle Power
  description: Toggle the power state of the WiiM device.
  fields:
    entity_id:
      name: Entity
      description: Name of the WiiM entity to control.
      selector:
        entity:
          domain: media_player
          integration: wiim